// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package crowdstrike

import (
	"context"
	"reflect"

	"errors"
	"github.com/crowdstrike/pulumi-crowdstrike/sdk/go/crowdstrike/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This resource allows you to manage the default prevention policy for Mac hosts. Prevention policies allow you to manage what activity will trigger detections and preventions on your hosts. Destruction of this resource *will not* delete the default prevention policy or remove any configured settings.
//
// ## API Scopes
//
// The following API scopes are required:
//
// - Prevention policies | Read & Write
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/crowdstrike/pulumi-crowdstrike/sdk/go/crowdstrike"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := crowdstrike.NewDefaultPreventionPolicyMac(ctx, "default", &crowdstrike.DefaultPreventionPolicyMacArgs{
//				Description:   pulumi.String("managed by terraform"),
//				IoaRuleGroups: pulumi.StringArray{},
//				CloudAdwareAndPup: &crowdstrike.DefaultPreventionPolicyMacCloudAdwareAndPupArgs{
//					Detection:  pulumi.String("MODERATE"),
//					Prevention: pulumi.String("CAUTIOUS"),
//				},
//				CloudAntiMalware: &crowdstrike.DefaultPreventionPolicyMacCloudAntiMalwareArgs{
//					Detection:  pulumi.String("MODERATE"),
//					Prevention: pulumi.String("CAUTIOUS"),
//				},
//				SensorAntiMalware: &crowdstrike.DefaultPreventionPolicyMacSensorAntiMalwareArgs{
//					Detection:  pulumi.String("MODERATE"),
//					Prevention: pulumi.String("CAUTIOUS"),
//				},
//				SensorAdwareAndPup: &crowdstrike.DefaultPreventionPolicyMacSensorAdwareAndPupArgs{
//					Detection:  pulumi.String("MODERATE"),
//					Prevention: pulumi.String("CAUTIOUS"),
//				},
//				NotifyEndUsers:                           pulumi.Bool(true),
//				CustomBlocking:                           pulumi.Bool(true),
//				DetectOnWrite:                            pulumi.Bool(true),
//				IntelligenceSourcedThreats:               pulumi.Bool(true),
//				PreventSuspiciousProcesses:               pulumi.Bool(true),
//				Quarantine:                               pulumi.Bool(true),
//				QuarantineOnWrite:                        pulumi.Bool(true),
//				ScriptBasedExecutionMonitoring:           pulumi.Bool(true),
//				SensorTamperingProtection:                pulumi.Bool(true),
//				UploadUnknownExecutables:                 pulumi.Bool(true),
//				UploadUnknownDetectionRelatedExecutables: pulumi.Bool(true),
//				XpcomShell:                               pulumi.Bool(true),
//				KcPasswordDecoded:                        pulumi.Bool(true),
//				HashCollector:                            pulumi.Bool(true),
//				EmpyreBackdoor:                           pulumi.Bool(true),
//				ChopperWebshell:                          pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("defaultPreventionPolicyMac", _default)
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The windows default prevention policy can be imported by specifying the id.
//
// ```sh
// $ pulumi import crowdstrike:index/defaultPreventionPolicyMac:DefaultPreventionPolicyMac default 7fb858a949034a0cbca175f660f1e769
// ```
type DefaultPreventionPolicyMac struct {
	pulumi.CustomResourceState

	// Whether to enable the setting. Execution of a command shell was blocked and is indicative of the system hosting a Chopper web page.
	ChopperWebshell pulumi.BoolOutput `pulumi:"chopperWebshell"`
	// Use cloud-based machine learning informed by global analysis of executables to detect and prevent adware and potentially unwanted programs (PUP) for your online hosts.
	CloudAdwareAndPup DefaultPreventionPolicyMacCloudAdwareAndPupOutput `pulumi:"cloudAdwareAndPup"`
	// Use cloud-based machine learning informed by global analysis of executables to detect and prevent known malware for your online hosts.
	CloudAntiMalware DefaultPreventionPolicyMacCloudAntiMalwareOutput `pulumi:"cloudAntiMalware"`
	// Whether to enable the setting. Block processes matching hashes that you add to IOC Management with the action set to "Block" or "Block, hide detection".
	CustomBlocking pulumi.BoolOutput `pulumi:"customBlocking"`
	// Description of the prevention policy.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Whether to enable the setting. Use machine learning to analyze suspicious files when they're written to disk. To adjust detection sensitivity, change Anti-malware Detection levels in Sensor Machine Learning and Cloud Machine Learning.
	DetectOnWrite pulumi.BoolOutput `pulumi:"detectOnWrite"`
	// Whether to enable the setting. A process with behaviors indicative of the Empyre Backdoor was terminated.
	EmpyreBackdoor pulumi.BoolOutput `pulumi:"empyreBackdoor"`
	// Whether to enable the setting. An attempt to dump a user’s hashed password was blocked.
	HashCollector pulumi.BoolOutput `pulumi:"hashCollector"`
	// Whether to enable the setting. Block processes that CrowdStrike Intelligence analysts classify as malicious. These are focused on static hash-based IOCs.
	IntelligenceSourcedThreats pulumi.BoolOutput `pulumi:"intelligenceSourcedThreats"`
	// IOA Rule Group to attach to the prevention policy.
	IoaRuleGroups pulumi.StringArrayOutput `pulumi:"ioaRuleGroups"`
	// Whether to enable the setting. An attempt to recover a plaintext password via the kcpassword file was blocked.
	KcPasswordDecoded pulumi.BoolOutput   `pulumi:"kcPasswordDecoded"`
	LastUpdated       pulumi.StringOutput `pulumi:"lastUpdated"`
	// Whether to enable the setting. Show a pop-up notification to the end user when the Falcon sensor blocks, kills, or quarantines. See these messages in Console.app by searching for Process: Falcon Notifications.
	NotifyEndUsers pulumi.BoolOutput `pulumi:"notifyEndUsers"`
	// Whether to enable the setting. Block processes that CrowdStrike analysts classify as suspicious. These are focused on dynamic IOAs, such as malware, exploits and other threats.
	PreventSuspiciousProcesses pulumi.BoolOutput `pulumi:"preventSuspiciousProcesses"`
	// Whether to enable the setting. Quarantine executable files after they’re prevented by NGAV. When this is enabled, we recommend setting anti-malware prevention levels to Moderate or higher and not using other antivirus solutions.
	Quarantine pulumi.BoolOutput `pulumi:"quarantine"`
	// Whether to enable the setting. Use machine learning to quarantine suspicious files when they're written to disk. To adjust quarantine sensitivity, change Anti-malware Prevention levels in Sensor Machine Learning and Cloud Machine Learning.
	QuarantineOnWrite pulumi.BoolOutput `pulumi:"quarantineOnWrite"`
	// Whether to enable the setting. Provides visibility into suspicious scripts, including shell and other scripting languages.
	ScriptBasedExecutionMonitoring pulumi.BoolOutput `pulumi:"scriptBasedExecutionMonitoring"`
	// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent adware and potentially unwanted programs (PUP).
	SensorAdwareAndPup DefaultPreventionPolicyMacSensorAdwareAndPupOutput `pulumi:"sensorAdwareAndPup"`
	// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent malware.
	SensorAntiMalware DefaultPreventionPolicyMacSensorAntiMalwareOutput `pulumi:"sensorAntiMalware"`
	// Whether to enable the setting. Blocks attempts to tamper with the sensor. If disabled, the sensor still creates detections for tampering attempts but doesn’t block them. Disabling not recommended.
	SensorTamperingProtection pulumi.BoolOutput `pulumi:"sensorTamperingProtection"`
	// Whether to enable the setting. Upload all unknown detection-related executables for advanced analysis in the cloud.
	UploadUnknownDetectionRelatedExecutables pulumi.BoolOutput `pulumi:"uploadUnknownDetectionRelatedExecutables"`
	// Whether to enable the setting. Upload all unknown executables for advanced analysis in the cloud.
	UploadUnknownExecutables pulumi.BoolOutput `pulumi:"uploadUnknownExecutables"`
	// Whether to enable the setting. The execution of an XPCOM shell was blocked.
	XpcomShell pulumi.BoolOutput `pulumi:"xpcomShell"`
}

// NewDefaultPreventionPolicyMac registers a new resource with the given unique name, arguments, and options.
func NewDefaultPreventionPolicyMac(ctx *pulumi.Context,
	name string, args *DefaultPreventionPolicyMacArgs, opts ...pulumi.ResourceOption) (*DefaultPreventionPolicyMac, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.IoaRuleGroups == nil {
		return nil, errors.New("invalid value for required argument 'IoaRuleGroups'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultPreventionPolicyMac
	err := ctx.RegisterResource("crowdstrike:index/defaultPreventionPolicyMac:DefaultPreventionPolicyMac", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultPreventionPolicyMac gets an existing DefaultPreventionPolicyMac resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultPreventionPolicyMac(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultPreventionPolicyMacState, opts ...pulumi.ResourceOption) (*DefaultPreventionPolicyMac, error) {
	var resource DefaultPreventionPolicyMac
	err := ctx.ReadResource("crowdstrike:index/defaultPreventionPolicyMac:DefaultPreventionPolicyMac", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultPreventionPolicyMac resources.
type defaultPreventionPolicyMacState struct {
	// Whether to enable the setting. Execution of a command shell was blocked and is indicative of the system hosting a Chopper web page.
	ChopperWebshell *bool `pulumi:"chopperWebshell"`
	// Use cloud-based machine learning informed by global analysis of executables to detect and prevent adware and potentially unwanted programs (PUP) for your online hosts.
	CloudAdwareAndPup *DefaultPreventionPolicyMacCloudAdwareAndPup `pulumi:"cloudAdwareAndPup"`
	// Use cloud-based machine learning informed by global analysis of executables to detect and prevent known malware for your online hosts.
	CloudAntiMalware *DefaultPreventionPolicyMacCloudAntiMalware `pulumi:"cloudAntiMalware"`
	// Whether to enable the setting. Block processes matching hashes that you add to IOC Management with the action set to "Block" or "Block, hide detection".
	CustomBlocking *bool `pulumi:"customBlocking"`
	// Description of the prevention policy.
	Description *string `pulumi:"description"`
	// Whether to enable the setting. Use machine learning to analyze suspicious files when they're written to disk. To adjust detection sensitivity, change Anti-malware Detection levels in Sensor Machine Learning and Cloud Machine Learning.
	DetectOnWrite *bool `pulumi:"detectOnWrite"`
	// Whether to enable the setting. A process with behaviors indicative of the Empyre Backdoor was terminated.
	EmpyreBackdoor *bool `pulumi:"empyreBackdoor"`
	// Whether to enable the setting. An attempt to dump a user’s hashed password was blocked.
	HashCollector *bool `pulumi:"hashCollector"`
	// Whether to enable the setting. Block processes that CrowdStrike Intelligence analysts classify as malicious. These are focused on static hash-based IOCs.
	IntelligenceSourcedThreats *bool `pulumi:"intelligenceSourcedThreats"`
	// IOA Rule Group to attach to the prevention policy.
	IoaRuleGroups []string `pulumi:"ioaRuleGroups"`
	// Whether to enable the setting. An attempt to recover a plaintext password via the kcpassword file was blocked.
	KcPasswordDecoded *bool   `pulumi:"kcPasswordDecoded"`
	LastUpdated       *string `pulumi:"lastUpdated"`
	// Whether to enable the setting. Show a pop-up notification to the end user when the Falcon sensor blocks, kills, or quarantines. See these messages in Console.app by searching for Process: Falcon Notifications.
	NotifyEndUsers *bool `pulumi:"notifyEndUsers"`
	// Whether to enable the setting. Block processes that CrowdStrike analysts classify as suspicious. These are focused on dynamic IOAs, such as malware, exploits and other threats.
	PreventSuspiciousProcesses *bool `pulumi:"preventSuspiciousProcesses"`
	// Whether to enable the setting. Quarantine executable files after they’re prevented by NGAV. When this is enabled, we recommend setting anti-malware prevention levels to Moderate or higher and not using other antivirus solutions.
	Quarantine *bool `pulumi:"quarantine"`
	// Whether to enable the setting. Use machine learning to quarantine suspicious files when they're written to disk. To adjust quarantine sensitivity, change Anti-malware Prevention levels in Sensor Machine Learning and Cloud Machine Learning.
	QuarantineOnWrite *bool `pulumi:"quarantineOnWrite"`
	// Whether to enable the setting. Provides visibility into suspicious scripts, including shell and other scripting languages.
	ScriptBasedExecutionMonitoring *bool `pulumi:"scriptBasedExecutionMonitoring"`
	// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent adware and potentially unwanted programs (PUP).
	SensorAdwareAndPup *DefaultPreventionPolicyMacSensorAdwareAndPup `pulumi:"sensorAdwareAndPup"`
	// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent malware.
	SensorAntiMalware *DefaultPreventionPolicyMacSensorAntiMalware `pulumi:"sensorAntiMalware"`
	// Whether to enable the setting. Blocks attempts to tamper with the sensor. If disabled, the sensor still creates detections for tampering attempts but doesn’t block them. Disabling not recommended.
	SensorTamperingProtection *bool `pulumi:"sensorTamperingProtection"`
	// Whether to enable the setting. Upload all unknown detection-related executables for advanced analysis in the cloud.
	UploadUnknownDetectionRelatedExecutables *bool `pulumi:"uploadUnknownDetectionRelatedExecutables"`
	// Whether to enable the setting. Upload all unknown executables for advanced analysis in the cloud.
	UploadUnknownExecutables *bool `pulumi:"uploadUnknownExecutables"`
	// Whether to enable the setting. The execution of an XPCOM shell was blocked.
	XpcomShell *bool `pulumi:"xpcomShell"`
}

type DefaultPreventionPolicyMacState struct {
	// Whether to enable the setting. Execution of a command shell was blocked and is indicative of the system hosting a Chopper web page.
	ChopperWebshell pulumi.BoolPtrInput
	// Use cloud-based machine learning informed by global analysis of executables to detect and prevent adware and potentially unwanted programs (PUP) for your online hosts.
	CloudAdwareAndPup DefaultPreventionPolicyMacCloudAdwareAndPupPtrInput
	// Use cloud-based machine learning informed by global analysis of executables to detect and prevent known malware for your online hosts.
	CloudAntiMalware DefaultPreventionPolicyMacCloudAntiMalwarePtrInput
	// Whether to enable the setting. Block processes matching hashes that you add to IOC Management with the action set to "Block" or "Block, hide detection".
	CustomBlocking pulumi.BoolPtrInput
	// Description of the prevention policy.
	Description pulumi.StringPtrInput
	// Whether to enable the setting. Use machine learning to analyze suspicious files when they're written to disk. To adjust detection sensitivity, change Anti-malware Detection levels in Sensor Machine Learning and Cloud Machine Learning.
	DetectOnWrite pulumi.BoolPtrInput
	// Whether to enable the setting. A process with behaviors indicative of the Empyre Backdoor was terminated.
	EmpyreBackdoor pulumi.BoolPtrInput
	// Whether to enable the setting. An attempt to dump a user’s hashed password was blocked.
	HashCollector pulumi.BoolPtrInput
	// Whether to enable the setting. Block processes that CrowdStrike Intelligence analysts classify as malicious. These are focused on static hash-based IOCs.
	IntelligenceSourcedThreats pulumi.BoolPtrInput
	// IOA Rule Group to attach to the prevention policy.
	IoaRuleGroups pulumi.StringArrayInput
	// Whether to enable the setting. An attempt to recover a plaintext password via the kcpassword file was blocked.
	KcPasswordDecoded pulumi.BoolPtrInput
	LastUpdated       pulumi.StringPtrInput
	// Whether to enable the setting. Show a pop-up notification to the end user when the Falcon sensor blocks, kills, or quarantines. See these messages in Console.app by searching for Process: Falcon Notifications.
	NotifyEndUsers pulumi.BoolPtrInput
	// Whether to enable the setting. Block processes that CrowdStrike analysts classify as suspicious. These are focused on dynamic IOAs, such as malware, exploits and other threats.
	PreventSuspiciousProcesses pulumi.BoolPtrInput
	// Whether to enable the setting. Quarantine executable files after they’re prevented by NGAV. When this is enabled, we recommend setting anti-malware prevention levels to Moderate or higher and not using other antivirus solutions.
	Quarantine pulumi.BoolPtrInput
	// Whether to enable the setting. Use machine learning to quarantine suspicious files when they're written to disk. To adjust quarantine sensitivity, change Anti-malware Prevention levels in Sensor Machine Learning and Cloud Machine Learning.
	QuarantineOnWrite pulumi.BoolPtrInput
	// Whether to enable the setting. Provides visibility into suspicious scripts, including shell and other scripting languages.
	ScriptBasedExecutionMonitoring pulumi.BoolPtrInput
	// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent adware and potentially unwanted programs (PUP).
	SensorAdwareAndPup DefaultPreventionPolicyMacSensorAdwareAndPupPtrInput
	// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent malware.
	SensorAntiMalware DefaultPreventionPolicyMacSensorAntiMalwarePtrInput
	// Whether to enable the setting. Blocks attempts to tamper with the sensor. If disabled, the sensor still creates detections for tampering attempts but doesn’t block them. Disabling not recommended.
	SensorTamperingProtection pulumi.BoolPtrInput
	// Whether to enable the setting. Upload all unknown detection-related executables for advanced analysis in the cloud.
	UploadUnknownDetectionRelatedExecutables pulumi.BoolPtrInput
	// Whether to enable the setting. Upload all unknown executables for advanced analysis in the cloud.
	UploadUnknownExecutables pulumi.BoolPtrInput
	// Whether to enable the setting. The execution of an XPCOM shell was blocked.
	XpcomShell pulumi.BoolPtrInput
}

func (DefaultPreventionPolicyMacState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPreventionPolicyMacState)(nil)).Elem()
}

type defaultPreventionPolicyMacArgs struct {
	// Whether to enable the setting. Execution of a command shell was blocked and is indicative of the system hosting a Chopper web page.
	ChopperWebshell *bool `pulumi:"chopperWebshell"`
	// Use cloud-based machine learning informed by global analysis of executables to detect and prevent adware and potentially unwanted programs (PUP) for your online hosts.
	CloudAdwareAndPup *DefaultPreventionPolicyMacCloudAdwareAndPup `pulumi:"cloudAdwareAndPup"`
	// Use cloud-based machine learning informed by global analysis of executables to detect and prevent known malware for your online hosts.
	CloudAntiMalware *DefaultPreventionPolicyMacCloudAntiMalware `pulumi:"cloudAntiMalware"`
	// Whether to enable the setting. Block processes matching hashes that you add to IOC Management with the action set to "Block" or "Block, hide detection".
	CustomBlocking *bool `pulumi:"customBlocking"`
	// Description of the prevention policy.
	Description *string `pulumi:"description"`
	// Whether to enable the setting. Use machine learning to analyze suspicious files when they're written to disk. To adjust detection sensitivity, change Anti-malware Detection levels in Sensor Machine Learning and Cloud Machine Learning.
	DetectOnWrite *bool `pulumi:"detectOnWrite"`
	// Whether to enable the setting. A process with behaviors indicative of the Empyre Backdoor was terminated.
	EmpyreBackdoor *bool `pulumi:"empyreBackdoor"`
	// Whether to enable the setting. An attempt to dump a user’s hashed password was blocked.
	HashCollector *bool `pulumi:"hashCollector"`
	// Whether to enable the setting. Block processes that CrowdStrike Intelligence analysts classify as malicious. These are focused on static hash-based IOCs.
	IntelligenceSourcedThreats *bool `pulumi:"intelligenceSourcedThreats"`
	// IOA Rule Group to attach to the prevention policy.
	IoaRuleGroups []string `pulumi:"ioaRuleGroups"`
	// Whether to enable the setting. An attempt to recover a plaintext password via the kcpassword file was blocked.
	KcPasswordDecoded *bool `pulumi:"kcPasswordDecoded"`
	// Whether to enable the setting. Show a pop-up notification to the end user when the Falcon sensor blocks, kills, or quarantines. See these messages in Console.app by searching for Process: Falcon Notifications.
	NotifyEndUsers *bool `pulumi:"notifyEndUsers"`
	// Whether to enable the setting. Block processes that CrowdStrike analysts classify as suspicious. These are focused on dynamic IOAs, such as malware, exploits and other threats.
	PreventSuspiciousProcesses *bool `pulumi:"preventSuspiciousProcesses"`
	// Whether to enable the setting. Quarantine executable files after they’re prevented by NGAV. When this is enabled, we recommend setting anti-malware prevention levels to Moderate or higher and not using other antivirus solutions.
	Quarantine *bool `pulumi:"quarantine"`
	// Whether to enable the setting. Use machine learning to quarantine suspicious files when they're written to disk. To adjust quarantine sensitivity, change Anti-malware Prevention levels in Sensor Machine Learning and Cloud Machine Learning.
	QuarantineOnWrite *bool `pulumi:"quarantineOnWrite"`
	// Whether to enable the setting. Provides visibility into suspicious scripts, including shell and other scripting languages.
	ScriptBasedExecutionMonitoring *bool `pulumi:"scriptBasedExecutionMonitoring"`
	// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent adware and potentially unwanted programs (PUP).
	SensorAdwareAndPup *DefaultPreventionPolicyMacSensorAdwareAndPup `pulumi:"sensorAdwareAndPup"`
	// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent malware.
	SensorAntiMalware *DefaultPreventionPolicyMacSensorAntiMalware `pulumi:"sensorAntiMalware"`
	// Whether to enable the setting. Blocks attempts to tamper with the sensor. If disabled, the sensor still creates detections for tampering attempts but doesn’t block them. Disabling not recommended.
	SensorTamperingProtection *bool `pulumi:"sensorTamperingProtection"`
	// Whether to enable the setting. Upload all unknown detection-related executables for advanced analysis in the cloud.
	UploadUnknownDetectionRelatedExecutables *bool `pulumi:"uploadUnknownDetectionRelatedExecutables"`
	// Whether to enable the setting. Upload all unknown executables for advanced analysis in the cloud.
	UploadUnknownExecutables *bool `pulumi:"uploadUnknownExecutables"`
	// Whether to enable the setting. The execution of an XPCOM shell was blocked.
	XpcomShell *bool `pulumi:"xpcomShell"`
}

// The set of arguments for constructing a DefaultPreventionPolicyMac resource.
type DefaultPreventionPolicyMacArgs struct {
	// Whether to enable the setting. Execution of a command shell was blocked and is indicative of the system hosting a Chopper web page.
	ChopperWebshell pulumi.BoolPtrInput
	// Use cloud-based machine learning informed by global analysis of executables to detect and prevent adware and potentially unwanted programs (PUP) for your online hosts.
	CloudAdwareAndPup DefaultPreventionPolicyMacCloudAdwareAndPupPtrInput
	// Use cloud-based machine learning informed by global analysis of executables to detect and prevent known malware for your online hosts.
	CloudAntiMalware DefaultPreventionPolicyMacCloudAntiMalwarePtrInput
	// Whether to enable the setting. Block processes matching hashes that you add to IOC Management with the action set to "Block" or "Block, hide detection".
	CustomBlocking pulumi.BoolPtrInput
	// Description of the prevention policy.
	Description pulumi.StringPtrInput
	// Whether to enable the setting. Use machine learning to analyze suspicious files when they're written to disk. To adjust detection sensitivity, change Anti-malware Detection levels in Sensor Machine Learning and Cloud Machine Learning.
	DetectOnWrite pulumi.BoolPtrInput
	// Whether to enable the setting. A process with behaviors indicative of the Empyre Backdoor was terminated.
	EmpyreBackdoor pulumi.BoolPtrInput
	// Whether to enable the setting. An attempt to dump a user’s hashed password was blocked.
	HashCollector pulumi.BoolPtrInput
	// Whether to enable the setting. Block processes that CrowdStrike Intelligence analysts classify as malicious. These are focused on static hash-based IOCs.
	IntelligenceSourcedThreats pulumi.BoolPtrInput
	// IOA Rule Group to attach to the prevention policy.
	IoaRuleGroups pulumi.StringArrayInput
	// Whether to enable the setting. An attempt to recover a plaintext password via the kcpassword file was blocked.
	KcPasswordDecoded pulumi.BoolPtrInput
	// Whether to enable the setting. Show a pop-up notification to the end user when the Falcon sensor blocks, kills, or quarantines. See these messages in Console.app by searching for Process: Falcon Notifications.
	NotifyEndUsers pulumi.BoolPtrInput
	// Whether to enable the setting. Block processes that CrowdStrike analysts classify as suspicious. These are focused on dynamic IOAs, such as malware, exploits and other threats.
	PreventSuspiciousProcesses pulumi.BoolPtrInput
	// Whether to enable the setting. Quarantine executable files after they’re prevented by NGAV. When this is enabled, we recommend setting anti-malware prevention levels to Moderate or higher and not using other antivirus solutions.
	Quarantine pulumi.BoolPtrInput
	// Whether to enable the setting. Use machine learning to quarantine suspicious files when they're written to disk. To adjust quarantine sensitivity, change Anti-malware Prevention levels in Sensor Machine Learning and Cloud Machine Learning.
	QuarantineOnWrite pulumi.BoolPtrInput
	// Whether to enable the setting. Provides visibility into suspicious scripts, including shell and other scripting languages.
	ScriptBasedExecutionMonitoring pulumi.BoolPtrInput
	// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent adware and potentially unwanted programs (PUP).
	SensorAdwareAndPup DefaultPreventionPolicyMacSensorAdwareAndPupPtrInput
	// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent malware.
	SensorAntiMalware DefaultPreventionPolicyMacSensorAntiMalwarePtrInput
	// Whether to enable the setting. Blocks attempts to tamper with the sensor. If disabled, the sensor still creates detections for tampering attempts but doesn’t block them. Disabling not recommended.
	SensorTamperingProtection pulumi.BoolPtrInput
	// Whether to enable the setting. Upload all unknown detection-related executables for advanced analysis in the cloud.
	UploadUnknownDetectionRelatedExecutables pulumi.BoolPtrInput
	// Whether to enable the setting. Upload all unknown executables for advanced analysis in the cloud.
	UploadUnknownExecutables pulumi.BoolPtrInput
	// Whether to enable the setting. The execution of an XPCOM shell was blocked.
	XpcomShell pulumi.BoolPtrInput
}

func (DefaultPreventionPolicyMacArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPreventionPolicyMacArgs)(nil)).Elem()
}

type DefaultPreventionPolicyMacInput interface {
	pulumi.Input

	ToDefaultPreventionPolicyMacOutput() DefaultPreventionPolicyMacOutput
	ToDefaultPreventionPolicyMacOutputWithContext(ctx context.Context) DefaultPreventionPolicyMacOutput
}

func (*DefaultPreventionPolicyMac) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPreventionPolicyMac)(nil)).Elem()
}

func (i *DefaultPreventionPolicyMac) ToDefaultPreventionPolicyMacOutput() DefaultPreventionPolicyMacOutput {
	return i.ToDefaultPreventionPolicyMacOutputWithContext(context.Background())
}

func (i *DefaultPreventionPolicyMac) ToDefaultPreventionPolicyMacOutputWithContext(ctx context.Context) DefaultPreventionPolicyMacOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultPreventionPolicyMacOutput)
}

// DefaultPreventionPolicyMacArrayInput is an input type that accepts DefaultPreventionPolicyMacArray and DefaultPreventionPolicyMacArrayOutput values.
// You can construct a concrete instance of `DefaultPreventionPolicyMacArrayInput` via:
//
//	DefaultPreventionPolicyMacArray{ DefaultPreventionPolicyMacArgs{...} }
type DefaultPreventionPolicyMacArrayInput interface {
	pulumi.Input

	ToDefaultPreventionPolicyMacArrayOutput() DefaultPreventionPolicyMacArrayOutput
	ToDefaultPreventionPolicyMacArrayOutputWithContext(context.Context) DefaultPreventionPolicyMacArrayOutput
}

type DefaultPreventionPolicyMacArray []DefaultPreventionPolicyMacInput

func (DefaultPreventionPolicyMacArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DefaultPreventionPolicyMac)(nil)).Elem()
}

func (i DefaultPreventionPolicyMacArray) ToDefaultPreventionPolicyMacArrayOutput() DefaultPreventionPolicyMacArrayOutput {
	return i.ToDefaultPreventionPolicyMacArrayOutputWithContext(context.Background())
}

func (i DefaultPreventionPolicyMacArray) ToDefaultPreventionPolicyMacArrayOutputWithContext(ctx context.Context) DefaultPreventionPolicyMacArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultPreventionPolicyMacArrayOutput)
}

// DefaultPreventionPolicyMacMapInput is an input type that accepts DefaultPreventionPolicyMacMap and DefaultPreventionPolicyMacMapOutput values.
// You can construct a concrete instance of `DefaultPreventionPolicyMacMapInput` via:
//
//	DefaultPreventionPolicyMacMap{ "key": DefaultPreventionPolicyMacArgs{...} }
type DefaultPreventionPolicyMacMapInput interface {
	pulumi.Input

	ToDefaultPreventionPolicyMacMapOutput() DefaultPreventionPolicyMacMapOutput
	ToDefaultPreventionPolicyMacMapOutputWithContext(context.Context) DefaultPreventionPolicyMacMapOutput
}

type DefaultPreventionPolicyMacMap map[string]DefaultPreventionPolicyMacInput

func (DefaultPreventionPolicyMacMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DefaultPreventionPolicyMac)(nil)).Elem()
}

func (i DefaultPreventionPolicyMacMap) ToDefaultPreventionPolicyMacMapOutput() DefaultPreventionPolicyMacMapOutput {
	return i.ToDefaultPreventionPolicyMacMapOutputWithContext(context.Background())
}

func (i DefaultPreventionPolicyMacMap) ToDefaultPreventionPolicyMacMapOutputWithContext(ctx context.Context) DefaultPreventionPolicyMacMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultPreventionPolicyMacMapOutput)
}

type DefaultPreventionPolicyMacOutput struct{ *pulumi.OutputState }

func (DefaultPreventionPolicyMacOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPreventionPolicyMac)(nil)).Elem()
}

func (o DefaultPreventionPolicyMacOutput) ToDefaultPreventionPolicyMacOutput() DefaultPreventionPolicyMacOutput {
	return o
}

func (o DefaultPreventionPolicyMacOutput) ToDefaultPreventionPolicyMacOutputWithContext(ctx context.Context) DefaultPreventionPolicyMacOutput {
	return o
}

// Whether to enable the setting. Execution of a command shell was blocked and is indicative of the system hosting a Chopper web page.
func (o DefaultPreventionPolicyMacOutput) ChopperWebshell() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.ChopperWebshell }).(pulumi.BoolOutput)
}

// Use cloud-based machine learning informed by global analysis of executables to detect and prevent adware and potentially unwanted programs (PUP) for your online hosts.
func (o DefaultPreventionPolicyMacOutput) CloudAdwareAndPup() DefaultPreventionPolicyMacCloudAdwareAndPupOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) DefaultPreventionPolicyMacCloudAdwareAndPupOutput {
		return v.CloudAdwareAndPup
	}).(DefaultPreventionPolicyMacCloudAdwareAndPupOutput)
}

// Use cloud-based machine learning informed by global analysis of executables to detect and prevent known malware for your online hosts.
func (o DefaultPreventionPolicyMacOutput) CloudAntiMalware() DefaultPreventionPolicyMacCloudAntiMalwareOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) DefaultPreventionPolicyMacCloudAntiMalwareOutput {
		return v.CloudAntiMalware
	}).(DefaultPreventionPolicyMacCloudAntiMalwareOutput)
}

// Whether to enable the setting. Block processes matching hashes that you add to IOC Management with the action set to "Block" or "Block, hide detection".
func (o DefaultPreventionPolicyMacOutput) CustomBlocking() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.CustomBlocking }).(pulumi.BoolOutput)
}

// Description of the prevention policy.
func (o DefaultPreventionPolicyMacOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Whether to enable the setting. Use machine learning to analyze suspicious files when they're written to disk. To adjust detection sensitivity, change Anti-malware Detection levels in Sensor Machine Learning and Cloud Machine Learning.
func (o DefaultPreventionPolicyMacOutput) DetectOnWrite() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.DetectOnWrite }).(pulumi.BoolOutput)
}

// Whether to enable the setting. A process with behaviors indicative of the Empyre Backdoor was terminated.
func (o DefaultPreventionPolicyMacOutput) EmpyreBackdoor() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.EmpyreBackdoor }).(pulumi.BoolOutput)
}

// Whether to enable the setting. An attempt to dump a user’s hashed password was blocked.
func (o DefaultPreventionPolicyMacOutput) HashCollector() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.HashCollector }).(pulumi.BoolOutput)
}

// Whether to enable the setting. Block processes that CrowdStrike Intelligence analysts classify as malicious. These are focused on static hash-based IOCs.
func (o DefaultPreventionPolicyMacOutput) IntelligenceSourcedThreats() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.IntelligenceSourcedThreats }).(pulumi.BoolOutput)
}

// IOA Rule Group to attach to the prevention policy.
func (o DefaultPreventionPolicyMacOutput) IoaRuleGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.StringArrayOutput { return v.IoaRuleGroups }).(pulumi.StringArrayOutput)
}

// Whether to enable the setting. An attempt to recover a plaintext password via the kcpassword file was blocked.
func (o DefaultPreventionPolicyMacOutput) KcPasswordDecoded() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.KcPasswordDecoded }).(pulumi.BoolOutput)
}

func (o DefaultPreventionPolicyMacOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

// Whether to enable the setting. Show a pop-up notification to the end user when the Falcon sensor blocks, kills, or quarantines. See these messages in Console.app by searching for Process: Falcon Notifications.
func (o DefaultPreventionPolicyMacOutput) NotifyEndUsers() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.NotifyEndUsers }).(pulumi.BoolOutput)
}

// Whether to enable the setting. Block processes that CrowdStrike analysts classify as suspicious. These are focused on dynamic IOAs, such as malware, exploits and other threats.
func (o DefaultPreventionPolicyMacOutput) PreventSuspiciousProcesses() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.PreventSuspiciousProcesses }).(pulumi.BoolOutput)
}

// Whether to enable the setting. Quarantine executable files after they’re prevented by NGAV. When this is enabled, we recommend setting anti-malware prevention levels to Moderate or higher and not using other antivirus solutions.
func (o DefaultPreventionPolicyMacOutput) Quarantine() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.Quarantine }).(pulumi.BoolOutput)
}

// Whether to enable the setting. Use machine learning to quarantine suspicious files when they're written to disk. To adjust quarantine sensitivity, change Anti-malware Prevention levels in Sensor Machine Learning and Cloud Machine Learning.
func (o DefaultPreventionPolicyMacOutput) QuarantineOnWrite() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.QuarantineOnWrite }).(pulumi.BoolOutput)
}

// Whether to enable the setting. Provides visibility into suspicious scripts, including shell and other scripting languages.
func (o DefaultPreventionPolicyMacOutput) ScriptBasedExecutionMonitoring() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.ScriptBasedExecutionMonitoring }).(pulumi.BoolOutput)
}

// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent adware and potentially unwanted programs (PUP).
func (o DefaultPreventionPolicyMacOutput) SensorAdwareAndPup() DefaultPreventionPolicyMacSensorAdwareAndPupOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) DefaultPreventionPolicyMacSensorAdwareAndPupOutput {
		return v.SensorAdwareAndPup
	}).(DefaultPreventionPolicyMacSensorAdwareAndPupOutput)
}

// For offline and online hosts, use sensor-based machine learning to identify and analyze unknown executables as they run to detect and prevent malware.
func (o DefaultPreventionPolicyMacOutput) SensorAntiMalware() DefaultPreventionPolicyMacSensorAntiMalwareOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) DefaultPreventionPolicyMacSensorAntiMalwareOutput {
		return v.SensorAntiMalware
	}).(DefaultPreventionPolicyMacSensorAntiMalwareOutput)
}

// Whether to enable the setting. Blocks attempts to tamper with the sensor. If disabled, the sensor still creates detections for tampering attempts but doesn’t block them. Disabling not recommended.
func (o DefaultPreventionPolicyMacOutput) SensorTamperingProtection() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.SensorTamperingProtection }).(pulumi.BoolOutput)
}

// Whether to enable the setting. Upload all unknown detection-related executables for advanced analysis in the cloud.
func (o DefaultPreventionPolicyMacOutput) UploadUnknownDetectionRelatedExecutables() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput {
		return v.UploadUnknownDetectionRelatedExecutables
	}).(pulumi.BoolOutput)
}

// Whether to enable the setting. Upload all unknown executables for advanced analysis in the cloud.
func (o DefaultPreventionPolicyMacOutput) UploadUnknownExecutables() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.UploadUnknownExecutables }).(pulumi.BoolOutput)
}

// Whether to enable the setting. The execution of an XPCOM shell was blocked.
func (o DefaultPreventionPolicyMacOutput) XpcomShell() pulumi.BoolOutput {
	return o.ApplyT(func(v *DefaultPreventionPolicyMac) pulumi.BoolOutput { return v.XpcomShell }).(pulumi.BoolOutput)
}

type DefaultPreventionPolicyMacArrayOutput struct{ *pulumi.OutputState }

func (DefaultPreventionPolicyMacArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DefaultPreventionPolicyMac)(nil)).Elem()
}

func (o DefaultPreventionPolicyMacArrayOutput) ToDefaultPreventionPolicyMacArrayOutput() DefaultPreventionPolicyMacArrayOutput {
	return o
}

func (o DefaultPreventionPolicyMacArrayOutput) ToDefaultPreventionPolicyMacArrayOutputWithContext(ctx context.Context) DefaultPreventionPolicyMacArrayOutput {
	return o
}

func (o DefaultPreventionPolicyMacArrayOutput) Index(i pulumi.IntInput) DefaultPreventionPolicyMacOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DefaultPreventionPolicyMac {
		return vs[0].([]*DefaultPreventionPolicyMac)[vs[1].(int)]
	}).(DefaultPreventionPolicyMacOutput)
}

type DefaultPreventionPolicyMacMapOutput struct{ *pulumi.OutputState }

func (DefaultPreventionPolicyMacMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DefaultPreventionPolicyMac)(nil)).Elem()
}

func (o DefaultPreventionPolicyMacMapOutput) ToDefaultPreventionPolicyMacMapOutput() DefaultPreventionPolicyMacMapOutput {
	return o
}

func (o DefaultPreventionPolicyMacMapOutput) ToDefaultPreventionPolicyMacMapOutputWithContext(ctx context.Context) DefaultPreventionPolicyMacMapOutput {
	return o
}

func (o DefaultPreventionPolicyMacMapOutput) MapIndex(k pulumi.StringInput) DefaultPreventionPolicyMacOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DefaultPreventionPolicyMac {
		return vs[0].(map[string]*DefaultPreventionPolicyMac)[vs[1].(string)]
	}).(DefaultPreventionPolicyMacOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultPreventionPolicyMacInput)(nil)).Elem(), &DefaultPreventionPolicyMac{})
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultPreventionPolicyMacArrayInput)(nil)).Elem(), DefaultPreventionPolicyMacArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultPreventionPolicyMacMapInput)(nil)).Elem(), DefaultPreventionPolicyMacMap{})
	pulumi.RegisterOutputType(DefaultPreventionPolicyMacOutput{})
	pulumi.RegisterOutputType(DefaultPreventionPolicyMacArrayOutput{})
	pulumi.RegisterOutputType(DefaultPreventionPolicyMacMapOutput{})
}
