// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package crowdstrike

import (
	"context"
	"reflect"

	"errors"
	"github.com/crowdstrike/pulumi-crowdstrike/sdk/go/crowdstrike/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This resource allows managing the host groups and ioa rule groups attached to a prevention policy. This resource takes exclusive ownership over the host groups and ioa rule groups assigned to a prevention policy. If you want to fully create or manage a prevention policy please use the `prevention_policy_*` resource for the platform you want to manage.
//
// ## API Scopes
//
// The following API scopes are required:
//
// - Prevention policies | Read & Write
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/crowdstrike/pulumi-crowdstrike/sdk/go/crowdstrike"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			example, err := crowdstrike.NewPreventionPolicyAttachment(ctx, "example", &crowdstrike.PreventionPolicyAttachmentArgs{
//				IdProperty: pulumi.String("16c0eecfeebb47ce95185fda2e5b3112"),
//				HostGroups: pulumi.StringArray{
//					pulumi.String("df868c936cd443e5a95b2603e2483602"),
//				},
//				IoaRuleGroups: pulumi.StringArray{
//					pulumi.String("507117bc669d41bb93d0a009f557bb23"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("preventionPolicyAttachment", example)
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Prevention Policy Attachment can be imported by specifying the id.
//
// ```sh
// $ pulumi import crowdstrike:index/preventionPolicyAttachment:PreventionPolicyAttachment example 7fb858a949034a0cbca175f660f1e769
// ```
type PreventionPolicyAttachment struct {
	pulumi.CustomResourceState

	// Host Group ids to attach to the prevention policy.
	HostGroups pulumi.StringArrayOutput `pulumi:"hostGroups"`
	// The prevention policy id you want to attach to.
	IdProperty pulumi.StringOutput `pulumi:"idProperty"`
	// IOA Rule Group to attach to the prevention policy.
	IoaRuleGroups pulumi.StringArrayOutput `pulumi:"ioaRuleGroups"`
	LastUpdated   pulumi.StringOutput      `pulumi:"lastUpdated"`
}

// NewPreventionPolicyAttachment registers a new resource with the given unique name, arguments, and options.
func NewPreventionPolicyAttachment(ctx *pulumi.Context,
	name string, args *PreventionPolicyAttachmentArgs, opts ...pulumi.ResourceOption) (*PreventionPolicyAttachment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.IdProperty == nil {
		return nil, errors.New("invalid value for required argument 'IdProperty'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PreventionPolicyAttachment
	err := ctx.RegisterResource("crowdstrike:index/preventionPolicyAttachment:PreventionPolicyAttachment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPreventionPolicyAttachment gets an existing PreventionPolicyAttachment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPreventionPolicyAttachment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PreventionPolicyAttachmentState, opts ...pulumi.ResourceOption) (*PreventionPolicyAttachment, error) {
	var resource PreventionPolicyAttachment
	err := ctx.ReadResource("crowdstrike:index/preventionPolicyAttachment:PreventionPolicyAttachment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PreventionPolicyAttachment resources.
type preventionPolicyAttachmentState struct {
	// Host Group ids to attach to the prevention policy.
	HostGroups []string `pulumi:"hostGroups"`
	// The prevention policy id you want to attach to.
	IdProperty *string `pulumi:"idProperty"`
	// IOA Rule Group to attach to the prevention policy.
	IoaRuleGroups []string `pulumi:"ioaRuleGroups"`
	LastUpdated   *string  `pulumi:"lastUpdated"`
}

type PreventionPolicyAttachmentState struct {
	// Host Group ids to attach to the prevention policy.
	HostGroups pulumi.StringArrayInput
	// The prevention policy id you want to attach to.
	IdProperty pulumi.StringPtrInput
	// IOA Rule Group to attach to the prevention policy.
	IoaRuleGroups pulumi.StringArrayInput
	LastUpdated   pulumi.StringPtrInput
}

func (PreventionPolicyAttachmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*preventionPolicyAttachmentState)(nil)).Elem()
}

type preventionPolicyAttachmentArgs struct {
	// Host Group ids to attach to the prevention policy.
	HostGroups []string `pulumi:"hostGroups"`
	// The prevention policy id you want to attach to.
	IdProperty string `pulumi:"idProperty"`
	// IOA Rule Group to attach to the prevention policy.
	IoaRuleGroups []string `pulumi:"ioaRuleGroups"`
}

// The set of arguments for constructing a PreventionPolicyAttachment resource.
type PreventionPolicyAttachmentArgs struct {
	// Host Group ids to attach to the prevention policy.
	HostGroups pulumi.StringArrayInput
	// The prevention policy id you want to attach to.
	IdProperty pulumi.StringInput
	// IOA Rule Group to attach to the prevention policy.
	IoaRuleGroups pulumi.StringArrayInput
}

func (PreventionPolicyAttachmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*preventionPolicyAttachmentArgs)(nil)).Elem()
}

type PreventionPolicyAttachmentInput interface {
	pulumi.Input

	ToPreventionPolicyAttachmentOutput() PreventionPolicyAttachmentOutput
	ToPreventionPolicyAttachmentOutputWithContext(ctx context.Context) PreventionPolicyAttachmentOutput
}

func (*PreventionPolicyAttachment) ElementType() reflect.Type {
	return reflect.TypeOf((**PreventionPolicyAttachment)(nil)).Elem()
}

func (i *PreventionPolicyAttachment) ToPreventionPolicyAttachmentOutput() PreventionPolicyAttachmentOutput {
	return i.ToPreventionPolicyAttachmentOutputWithContext(context.Background())
}

func (i *PreventionPolicyAttachment) ToPreventionPolicyAttachmentOutputWithContext(ctx context.Context) PreventionPolicyAttachmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PreventionPolicyAttachmentOutput)
}

// PreventionPolicyAttachmentArrayInput is an input type that accepts PreventionPolicyAttachmentArray and PreventionPolicyAttachmentArrayOutput values.
// You can construct a concrete instance of `PreventionPolicyAttachmentArrayInput` via:
//
//	PreventionPolicyAttachmentArray{ PreventionPolicyAttachmentArgs{...} }
type PreventionPolicyAttachmentArrayInput interface {
	pulumi.Input

	ToPreventionPolicyAttachmentArrayOutput() PreventionPolicyAttachmentArrayOutput
	ToPreventionPolicyAttachmentArrayOutputWithContext(context.Context) PreventionPolicyAttachmentArrayOutput
}

type PreventionPolicyAttachmentArray []PreventionPolicyAttachmentInput

func (PreventionPolicyAttachmentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PreventionPolicyAttachment)(nil)).Elem()
}

func (i PreventionPolicyAttachmentArray) ToPreventionPolicyAttachmentArrayOutput() PreventionPolicyAttachmentArrayOutput {
	return i.ToPreventionPolicyAttachmentArrayOutputWithContext(context.Background())
}

func (i PreventionPolicyAttachmentArray) ToPreventionPolicyAttachmentArrayOutputWithContext(ctx context.Context) PreventionPolicyAttachmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PreventionPolicyAttachmentArrayOutput)
}

// PreventionPolicyAttachmentMapInput is an input type that accepts PreventionPolicyAttachmentMap and PreventionPolicyAttachmentMapOutput values.
// You can construct a concrete instance of `PreventionPolicyAttachmentMapInput` via:
//
//	PreventionPolicyAttachmentMap{ "key": PreventionPolicyAttachmentArgs{...} }
type PreventionPolicyAttachmentMapInput interface {
	pulumi.Input

	ToPreventionPolicyAttachmentMapOutput() PreventionPolicyAttachmentMapOutput
	ToPreventionPolicyAttachmentMapOutputWithContext(context.Context) PreventionPolicyAttachmentMapOutput
}

type PreventionPolicyAttachmentMap map[string]PreventionPolicyAttachmentInput

func (PreventionPolicyAttachmentMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PreventionPolicyAttachment)(nil)).Elem()
}

func (i PreventionPolicyAttachmentMap) ToPreventionPolicyAttachmentMapOutput() PreventionPolicyAttachmentMapOutput {
	return i.ToPreventionPolicyAttachmentMapOutputWithContext(context.Background())
}

func (i PreventionPolicyAttachmentMap) ToPreventionPolicyAttachmentMapOutputWithContext(ctx context.Context) PreventionPolicyAttachmentMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PreventionPolicyAttachmentMapOutput)
}

type PreventionPolicyAttachmentOutput struct{ *pulumi.OutputState }

func (PreventionPolicyAttachmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PreventionPolicyAttachment)(nil)).Elem()
}

func (o PreventionPolicyAttachmentOutput) ToPreventionPolicyAttachmentOutput() PreventionPolicyAttachmentOutput {
	return o
}

func (o PreventionPolicyAttachmentOutput) ToPreventionPolicyAttachmentOutputWithContext(ctx context.Context) PreventionPolicyAttachmentOutput {
	return o
}

// Host Group ids to attach to the prevention policy.
func (o PreventionPolicyAttachmentOutput) HostGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *PreventionPolicyAttachment) pulumi.StringArrayOutput { return v.HostGroups }).(pulumi.StringArrayOutput)
}

// The prevention policy id you want to attach to.
func (o PreventionPolicyAttachmentOutput) IdProperty() pulumi.StringOutput {
	return o.ApplyT(func(v *PreventionPolicyAttachment) pulumi.StringOutput { return v.IdProperty }).(pulumi.StringOutput)
}

// IOA Rule Group to attach to the prevention policy.
func (o PreventionPolicyAttachmentOutput) IoaRuleGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *PreventionPolicyAttachment) pulumi.StringArrayOutput { return v.IoaRuleGroups }).(pulumi.StringArrayOutput)
}

func (o PreventionPolicyAttachmentOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *PreventionPolicyAttachment) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

type PreventionPolicyAttachmentArrayOutput struct{ *pulumi.OutputState }

func (PreventionPolicyAttachmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PreventionPolicyAttachment)(nil)).Elem()
}

func (o PreventionPolicyAttachmentArrayOutput) ToPreventionPolicyAttachmentArrayOutput() PreventionPolicyAttachmentArrayOutput {
	return o
}

func (o PreventionPolicyAttachmentArrayOutput) ToPreventionPolicyAttachmentArrayOutputWithContext(ctx context.Context) PreventionPolicyAttachmentArrayOutput {
	return o
}

func (o PreventionPolicyAttachmentArrayOutput) Index(i pulumi.IntInput) PreventionPolicyAttachmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PreventionPolicyAttachment {
		return vs[0].([]*PreventionPolicyAttachment)[vs[1].(int)]
	}).(PreventionPolicyAttachmentOutput)
}

type PreventionPolicyAttachmentMapOutput struct{ *pulumi.OutputState }

func (PreventionPolicyAttachmentMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PreventionPolicyAttachment)(nil)).Elem()
}

func (o PreventionPolicyAttachmentMapOutput) ToPreventionPolicyAttachmentMapOutput() PreventionPolicyAttachmentMapOutput {
	return o
}

func (o PreventionPolicyAttachmentMapOutput) ToPreventionPolicyAttachmentMapOutputWithContext(ctx context.Context) PreventionPolicyAttachmentMapOutput {
	return o
}

func (o PreventionPolicyAttachmentMapOutput) MapIndex(k pulumi.StringInput) PreventionPolicyAttachmentOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PreventionPolicyAttachment {
		return vs[0].(map[string]*PreventionPolicyAttachment)[vs[1].(string)]
	}).(PreventionPolicyAttachmentOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PreventionPolicyAttachmentInput)(nil)).Elem(), &PreventionPolicyAttachment{})
	pulumi.RegisterInputType(reflect.TypeOf((*PreventionPolicyAttachmentArrayInput)(nil)).Elem(), PreventionPolicyAttachmentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PreventionPolicyAttachmentMapInput)(nil)).Elem(), PreventionPolicyAttachmentMap{})
	pulumi.RegisterOutputType(PreventionPolicyAttachmentOutput{})
	pulumi.RegisterOutputType(PreventionPolicyAttachmentArrayOutput{})
	pulumi.RegisterOutputType(PreventionPolicyAttachmentMapOutput{})
}
