// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CrowdStrike.Crowdstrike.Outputs
{

    [OutputType]
    public sealed class CloudAwsAccountAssetInventory
    {
        /// <summary>
        /// Enable asset inventory
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Custom AWS IAM role name
        /// </summary>
        public readonly string? RoleName;

        [OutputConstructor]
        private CloudAwsAccountAssetInventory(
            bool enabled,

            string? roleName)
        {
            Enabled = enabled;
            RoleName = roleName;
        }
    }
}
