// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CrowdStrike.Crowdstrike.Outputs
{

    [OutputType]
    public sealed class DefaultSensorUpdatePolicySchedule
    {
        /// <summary>
        /// Enable the scheduler for sensor update policy.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// The time block to prevent sensor updates. Only set when enabled is true.
        /// </summary>
        public readonly ImmutableArray<Outputs.DefaultSensorUpdatePolicyScheduleTimeBlock> TimeBlocks;
        /// <summary>
        /// The time zones that will be used for the time blocks. Only set when enabled is true.
        /// </summary>
        public readonly string? Timezone;

        [OutputConstructor]
        private DefaultSensorUpdatePolicySchedule(
            bool enabled,

            ImmutableArray<Outputs.DefaultSensorUpdatePolicyScheduleTimeBlock> timeBlocks,

            string? timezone)
        {
            Enabled = enabled;
            TimeBlocks = timeBlocks;
            Timezone = timezone;
        }
    }
}
