// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CrowdStrike.Crowdstrike.Outputs
{

    [OutputType]
    public sealed class GetSensorUpdatePolicyBuildsLinuxResult
    {
        /// <summary>
        /// All sensor builds for the specific platform.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSensorUpdatePolicyBuildsLinuxAllResult> Alls;
        /// <summary>
        /// The latest sensor build.
        /// </summary>
        public readonly Outputs.GetSensorUpdatePolicyBuildsLinuxLatestResult Latest;
        /// <summary>
        /// The n-1 sensor build.
        /// </summary>
        public readonly Outputs.GetSensorUpdatePolicyBuildsLinuxN1Result N1;
        /// <summary>
        /// The n-2 sensor build.
        /// </summary>
        public readonly Outputs.GetSensorUpdatePolicyBuildsLinuxN2Result N2;

        [OutputConstructor]
        private GetSensorUpdatePolicyBuildsLinuxResult(
            ImmutableArray<Outputs.GetSensorUpdatePolicyBuildsLinuxAllResult> alls,

            Outputs.GetSensorUpdatePolicyBuildsLinuxLatestResult latest,

            Outputs.GetSensorUpdatePolicyBuildsLinuxN1Result n1,

            Outputs.GetSensorUpdatePolicyBuildsLinuxN2Result n2)
        {
            Alls = alls;
            Latest = latest;
            N1 = n1;
            N2 = n2;
        }
    }
}
