// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CrowdStrike.Crowdstrike.Inputs
{

    public sealed class CloudAwsAccountIdpArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable Identity Protection
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// Current status of the Identity Protection integration
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public CloudAwsAccountIdpArgs()
        {
        }
        public static new CloudAwsAccountIdpArgs Empty => new CloudAwsAccountIdpArgs();
    }
}
