// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CrowdStrike.Crowdstrike.Inputs
{

    public sealed class CloudAwsAccountAssetInventoryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable asset inventory
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// Custom AWS IAM role name
        /// </summary>
        [Input("roleName")]
        public Input<string>? RoleName { get; set; }

        public CloudAwsAccountAssetInventoryArgs()
        {
        }
        public static new CloudAwsAccountAssetInventoryArgs Empty => new CloudAwsAccountAssetInventoryArgs();
    }
}
