// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CrowdStrike.Crowdstrike.Inputs
{

    public sealed class FilevantagePolicyScheduledExclusionRepeatedGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If the exclusion is all day.
        /// </summary>
        [Input("allDay", required: true)]
        public Input<bool> AllDay { get; set; } = null!;

        [Input("daysOfMonths")]
        private InputList<int>? _daysOfMonths;

        /// <summary>
        /// The days of the month to allow the exclusion. Required if frequency is set to monthly and monthly_occurrence is set to days. Options: 1-31
        /// </summary>
        public InputList<int> DaysOfMonths
        {
            get => _daysOfMonths ?? (_daysOfMonths = new InputList<int>());
            set => _daysOfMonths = value;
        }

        [Input("daysOfWeeks")]
        private InputList<string>? _daysOfWeeks;

        /// <summary>
        /// The days of the week to allow the exclusion. Required if frequency is set to weekly or set to monthly and monthly_occurrence is set to a week. Options: Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday
        /// </summary>
        public InputList<string> DaysOfWeeks
        {
            get => _daysOfWeeks ?? (_daysOfWeeks = new InputList<string>());
            set => _daysOfWeeks = value;
        }

        /// <summary>
        /// The end time to end the scheduled exclusion in 24 hour format. Format: HH:MM required if all_day is false
        /// </summary>
        [Input("endTime")]
        public Input<string>? EndTime { get; set; }

        /// <summary>
        /// The frequency of the exclusion. Options: daily, weekly, monthly
        /// </summary>
        [Input("frequency", required: true)]
        public Input<string> Frequency { get; set; } = null!;

        /// <summary>
        /// The monthly occurrence of the exclusion. Either specify a week (first, second, third, fourth) or set to days to specify days of the month. Options: first, second, third, fourth, days. Required if frequency is set to monthly
        /// </summary>
        [Input("monthlyOccurrence")]
        public Input<string>? MonthlyOccurrence { get; set; }

        /// <summary>
        /// The start time to allow the scheduled exclusion in 24 hour format. Format: HH:MM required if all_day is false
        /// </summary>
        [Input("startTime")]
        public Input<string>? StartTime { get; set; }

        public FilevantagePolicyScheduledExclusionRepeatedGetArgs()
        {
        }
        public static new FilevantagePolicyScheduledExclusionRepeatedGetArgs Empty => new FilevantagePolicyScheduledExclusionRepeatedGetArgs();
    }
}
