// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * This data source provides information about AWS accounts in Falcon.
 *
 * ## API Scopes
 *
 * The following API scopes are required:
 *
 * - Cloud security AWS registration | Read & Write
 * - CSPM registration | Read & Write
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as crowdstrike from "@pulumi/crowdstrike";
 *
 * const all = crowdstrike.getCloudAwsAccount({});
 * const specific = crowdstrike.getCloudAwsAccount({
 *     accountId: "123456789012",
 * });
 * const org = crowdstrike.getCloudAwsAccount({
 *     organizationId: "o-123456789012",
 * });
 * ```
 */
export function getCloudAwsAccount(args?: GetCloudAwsAccountArgs, opts?: pulumi.InvokeOptions): Promise<GetCloudAwsAccountResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("crowdstrike:index/getCloudAwsAccount:getCloudAwsAccount", {
        "accountId": args.accountId,
        "organizationId": args.organizationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getCloudAwsAccount.
 */
export interface GetCloudAwsAccountArgs {
    /**
     * Filter the results to a specific AWS Account ID. When specified, returns details for the matching AWS account. Can be used together with organizationId filter for OR matching
     */
    accountId?: string;
    /**
     * Filter the results to accounts within a specific AWS Organization. When specified, returns all AWS accounts associated with this organization ID. Can be used together with accountId filter for OR matching
     */
    organizationId?: string;
}

/**
 * A collection of values returned by getCloudAwsAccount.
 */
export interface GetCloudAwsAccountResult {
    /**
     * Filter the results to a specific AWS Account ID. When specified, returns details for the matching AWS account. Can be used together with organizationId filter for OR matching
     */
    readonly accountId?: string;
    /**
     * The list of AWS accounts
     */
    readonly accounts: outputs.GetCloudAwsAccountAccount[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Filter the results to accounts within a specific AWS Organization. When specified, returns all AWS accounts associated with this organization ID. Can be used together with accountId filter for OR matching
     */
    readonly organizationId?: string;
}
/**
 * This data source provides information about AWS accounts in Falcon.
 *
 * ## API Scopes
 *
 * The following API scopes are required:
 *
 * - Cloud security AWS registration | Read & Write
 * - CSPM registration | Read & Write
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as crowdstrike from "@pulumi/crowdstrike";
 *
 * const all = crowdstrike.getCloudAwsAccount({});
 * const specific = crowdstrike.getCloudAwsAccount({
 *     accountId: "123456789012",
 * });
 * const org = crowdstrike.getCloudAwsAccount({
 *     organizationId: "o-123456789012",
 * });
 * ```
 */
export function getCloudAwsAccountOutput(args?: GetCloudAwsAccountOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCloudAwsAccountResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("crowdstrike:index/getCloudAwsAccount:getCloudAwsAccount", {
        "accountId": args.accountId,
        "organizationId": args.organizationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getCloudAwsAccount.
 */
export interface GetCloudAwsAccountOutputArgs {
    /**
     * Filter the results to a specific AWS Account ID. When specified, returns details for the matching AWS account. Can be used together with organizationId filter for OR matching
     */
    accountId?: pulumi.Input<string>;
    /**
     * Filter the results to accounts within a specific AWS Organization. When specified, returns all AWS accounts associated with this organization ID. Can be used together with accountId filter for OR matching
     */
    organizationId?: pulumi.Input<string>;
}
